if(TARGET Boost::headers)
  return()
endif()
get_filename_component(_BOOST_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
add_library(Boost::headers INTERFACE IMPORTED)
set_target_properties(Boost::headers PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_BOOST_PREFIX}/include")
if(NOT TARGET AsApp::boost)
  add_library(AsApp::boost INTERFACE IMPORTED)
  set_target_properties(AsApp::boost PROPERTIES INTERFACE_LINK_LIBRARIES Boost::headers)
endif()
