if(TARGET spdlog::spdlog)
  return()
endif()
add_library(spdlog INTERFACE)
add_library(spdlog::spdlog ALIAS spdlog)
get_filename_component(_SPDLOG_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
target_include_directories(spdlog INTERFACE "${_SPDLOG_PREFIX}/include")
target_compile_definitions(spdlog INTERFACE SPDLOG_HEADER_ONLY)
