if(TARGET Boost::headers)
  return()
endif()
include("${CMAKE_CURRENT_LIST_DIR}/boostTargets.cmake")
if(TARGET Boost::boost_headers AND NOT TARGET Boost::headers)
  add_library(Boost::headers ALIAS Boost::boost_headers)
endif()
if(NOT TARGET AsApp::boost)
  add_library(AsApp::boost INTERFACE IMPORTED)
  set_target_properties(AsApp::boost PROPERTIES INTERFACE_LINK_LIBRARIES Boost::headers)
endif()
