if(TARGET AsApp::ffi)
  return()
endif()
get_filename_component(_FFI_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
set(_FFI_LIB "${_FFI_ROOT}/lib/libffi.so")
if(NOT EXISTS "${_FFI_LIB}")
  file(GLOB _FFI_CAND "${_FFI_ROOT}/lib/libffi.so.*")
  list(GET _FFI_CAND 0 _FFI_LIB)
endif()
add_library(AsApp::ffi SHARED IMPORTED)
set_target_properties(AsApp::ffi PROPERTIES
  IMPORTED_LOCATION "${_FFI_LIB}"
  INTERFACE_INCLUDE_DIRECTORIES "${_FFI_ROOT}/include")
if(NOT TARGET AsApp::libffi)
  add_library(AsApp::libffi INTERFACE IMPORTED)
  set_target_properties(AsApp::libffi PROPERTIES INTERFACE_LINK_LIBRARIES AsApp::ffi)
endif()
